### ISSUE TITLE
Should filename pattern be supported in regular expression format?

### ISSUE THREAD

**Issue by vutung2311** [roadrunner-server/reload#12]
My project has a file named `.phpunit.result.cache` and everytime this file changes. It triggerred a reload. I think with regular expression pattern this can be solve. What do you think?

**Comment by rustatian** [comment]
Hey @vutung2311 👋🏻. This plugin should be used only in the development environment, not in production. The purpose of it is to reload the Workers on changes. If you want to exclude this pattern, you may include only needed file extensions to track.
https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L989
